[general]
# List of award IDs you want monitored
awards = ["1909","2023","3008"]

[diff]
# Fields to ignore in diffing if too volatile (location often changes formatting)
ignore_fields = ["location"]

[notify]
# Choose "discord" or "email"
method = "email"

[discord]
# Put your Discord webhook URL here
webhook_url = "https://discord.com/api/webhooks/XXXX/XXXX"

[email]
# Only needed if method = "email"
smtp_host = "smtp-mail.outlook.com"
smtp_port = 587
username  = "setiawa@purdue.edu"
password  = "Tacotofu2020"   # use app password, not your normal password
to = ["mrakmalsetiawan@gmail.com"]
